<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Http;

/**
 * One-time setup command — run manually once per child app, not scheduled.
 * Exchanges a short-lived registration code (generated by an admin in the
 * parent's "Affiliates" screen) for this instance's real slug + shared
 * secret. Prints them for the operator to paste into .env themselves
 * rather than writing .env programmatically, which is easy to get wrong
 * (comments, ordering, other unrelated vars) on a file this sensitive.
 */
class ParentSyncRegister extends Command
{
    protected $signature = 'parent-sync:register {code? : The registration code from the parent admin} {--base-url= : Overrides PARENT_SYNC_BASE_URL for this call}';

    protected $description = 'Exchange a one-time registration code for this instance\'s parent-sync credentials';

    public function handle()
    {
        $code = $this->argument('code') ?: $this->ask('Registration code (from the parent admin)');
        $baseUrl = $this->option('base-url') ?: config('parent_sync.parent_base_url');

        if (!$code) {
            $this->error('A registration code is required.');
            return self::FAILURE;
        }

        if (!$baseUrl) {
            $this->error('No parent base URL configured — pass --base-url=https://... or set PARENT_SYNC_BASE_URL in .env first.');
            return self::FAILURE;
        }

        $url = rtrim($baseUrl, '/') . '/api/child/register';

        try {
            $response = Http::timeout(15)->post($url, ['registration_code' => $code]);
        } catch (\Throwable $e) {
            $this->error("Could not reach the parent: {$e->getMessage()}");
            return self::FAILURE;
        }

        if (!$response->successful()) {
            $this->error('Registration failed: ' . ($response->json('message') ?? $response->body()));
            return self::FAILURE;
        }

        $slug = $response->json('data.slug');
        $secret = $response->json('data.shared_secret');

        $this->info('Registered successfully. Add these to .env, then set PARENT_SYNC_ENABLED=true and PARENT_SYNC_DRY_RUN=false when ready:');
        $this->line('');
        $this->line("PARENT_SYNC_BASE_URL={$baseUrl}");
        $this->line("PARENT_SYNC_CHILD_SLUG={$slug}");
        $this->line("PARENT_SYNC_SECRET={$secret}");
        $this->line('');
        $this->warn('This secret is shown once — the parent never returns it again after this call.');

        return self::SUCCESS;
    }
}
